Cargo.toml, src/error.rs
Hi!
I found that you implement all the error stuff yourself. This can be done in a more simple way by deriving the `thiserror::Error` trait.
Enjoy! :wink:
=> Replace manual error impls with thiserror derive

Cargo.toml
There's no need to have env_logger in normal dependencies if it is only used in the examples.
This will conflict with #31, I will rebase as needed, of course!
=> Make env_logger dev-dependency

examples/mastodon_marker.rs, examples/pleroma_marker.rs, src/entities/marker.rs, src/mastodon/entities/marker.rs, src/mastodon/mastodon.rs, src/pleroma/entities/marker.rs, src/pleroma/pleroma.rs
1. Pleroma marker does not have `home` marker, it has only `notifications` marker.
2. Pleroma marker's timestamp does not contain the timezone, so it was the wrong format as DateTime. For example: `2020-04-07T13:49:36`
=> Fix pleroma marker entity

examples/mastodon_authorization.rs, examples/mastodon_post_with_media.rs, examples/pleroma_authorization.rs, examples/pleroma_post_with_media.rs, src/megalodon.rs
Hiya! Not a bug, just a little usability thing that I felt could be improved a little. A lot of the option structs are very `Option<T>`-heavy, and in several cases the user won't need all of the fields. This derive allows the user to initialize these structs in a much cleaner manner, without needing to put in several `field: None,`.
=> derive Default on Option-heavy structs to enable ..Default::default() pattern

src/mastodon/mastodon.rs
This fixes the `fields_attributes` being incorrectly referred to as Array instead of an Object (see [documentation](https://docs.joinmastodon.org/methods/accounts/#update_credentials)).
As this « Object » is supposed to be an ordered hash of some sorts, this makes sense to consider it as a Vector when calling the function `update_credentials` and transform it in said hash afterwards.
=> fix(mastodon): fields_attributes as hash instead of array

Cargo.toml, examples/mastodon_streaming.rs, src/error.rs, src/mastodon/web_socket.rs, src/pleroma/web_socket.rs
Rewrite with `tokio-tungstenite` and `tokio::time::timeout` for reading messages.
=> Auto-reconnect WebSocket with tokio-tungstenite

src/entities/tag.rs, src/mastodon/entities/tag.rs, src/pleroma/entities/tag.rs
I got the following error whenever I tried to retrieve the home timeline from the `mastodon.social` instance:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `following`", line: 1, column: 23826)', src/response.rs:39:56
```
I had a look at the json that was returned, and the `following` property wasn't there. And indeed, it is listed as `optional` [here](https://docs.joinmastodon.org/entities/Tag/#following). I've made the property optional on the related entities.
=> make `following` optional

src/mastodon/entities/notification.rs, src/pleroma/entities/notification.rs
Mastodon and Pleroma don't send poll vote events.
It only send poll expired events.
=> Fix poll events for pleroma and mastodon

src/mastodon/mastodon.rs, src/pleroma/pleroma.rs
I'm not sure if these are used for anything, but they're definitely spelled wrong.
=> Fix typo in token endpoint URL passed to BasicClient

src/entities/history.rs, src/mastodon/entities/history.rs, src/pleroma/entities/history.rs
This pull request adds a new function to parse string values to u64, usize and possibly other types and uses it to deserialize field values in the history mastodon entity.
=> Add parse_from_string for deserializing mastodon history entities

src/entities/notification.rs, src/mastodon/entities/notification.rs, src/pleroma/entities/notification.rs
This adds the `update` `enum` which I've been getting in notifications. It also adds `characters_reserved_per_url` back. I've modelled this as optional as it doesn't exist in Pleroma.
=> Add notification update

src/detector.rs, src/error.rs, src/lib.rs
All ActivityPub services have `/.well-known/nodeinfo` endpoint and the endpoint also provides an SNS type. So it is better to use this endpoint to detect SNS.
=> Use nodeinfo to detect SNS

src/entities/notification.rs, src/mastodon/entities/notification.rs
Mastodon will send an `admin.sign_up` type notification when an admin signup happens. This causes serde deserialization to fail.
This small change adds an `AdminSignup` variant to the `NotificationType` enum.
_(Be kind when reviewing this PR, as this is my first Rust project and I have only been writing Rust code for two months)._
=> Add support for admin.sign_up notification type

examples/friendica_relationship.rs, examples/mastodon_relationship.rs, examples/pleroma_relationship.rs, src/entities/relationship.rs, src/friendica/entities/relationship.rs, src/mastodon/entities/relationship.rs, src/pleroma/entities/relationship.rs
Because it is removed from Mastodon
=> Remove delivery_following from relationship

src/detector.rs
This is because Hometown is in every way that matters still a Mastodon service.
=> Treat Hometown as Mastodon

Cargo.toml, src/friendica/friendica.rs, src/mastodon/mastodon.rs, src/megalodon.rs, src/pleroma/pleroma.rs
An improved version of #95 
Since crate::generator returns a trait object, I had to make it dynamic dispatch.
追伸: お互い日本人っぽいので日本語で話しませんか?
=> Add upload_media_reader

examples/mastodon_search.rs, src/friendica/friendica.rs, src/mastodon/mastodon.rs, src/megalodon.rs, src/pleroma/pleroma.rs
`type` is an optional field according to the Mastodon document.
https://docs.joinmastodon.org/methods/search/
=> Put type param into options in search

examples/firefish_search.rs, src/firefish/firefish.rs
Even if status search fails, it should return accounts and hashtags results.
=> Ignore errors in Firefish search

Cargo.toml
If your project depends on `megalodon` your `cargo tree` looked like this:
```
├── megalodon v0.11.7
│   ├── async-trait v0.1.75 (proc-macro) (*)
│   ├── chrono v0.4.31 (*)
│   ├── futures-util v0.3.29 (*)
│   ├── hex v0.4.3
│   ├── http v0.2.11
│   │   ├── bytes v1.5.0
│   │   ├── fnv v1.0.7
│   │   └── itoa v1.0.10
│   ├── log v0.4.20
│   ├── oauth2 v4.4.2
│   │   ├── base64 v0.13.1
│   │   ├── chrono v0.4.31 (*)
│   │   ├── http v0.2.11 (*)
│   │   ├── rand v0.8.5 (*)
│   │   ├── reqwest v0.11.22
│   │   │   ├── base64 v0.21.5
│   │   │   ├── bytes v1.5.0
│   │   │   ├── encoding_rs v0.8.33
│   │   │   │   └── cfg-if v1.0.0
│   │   │   ├── futures-core v0.3.29
│   │   │   ├── futures-util v0.3.29 (*)
│   │   │   ├── h2 v0.3.22
│   │   │   │   ├── bytes v1.5.0
│   │   │   │   ├── fnv …
```
=> fix: disable default features for reqwest

examples/firefish_notifications.rs, src/detector.rs, src/entities/notification.rs, src/entities/reaction.rs, src/firefish/entities/notification.rs, src/firefish/entities/reaction.rs, src/friendica/entities/notification.rs, src/mastodon/entities/notification.rs, src/pleroma/entities/notification.rs, src/pleroma/entities/reaction.rs
Currently, Pleroma supports custom emoji reactions. 
I parsed custom emoji reactions to Reaction object that is shared with Firefish. As a result, `emoji` filed in Notification is deleted, please use `reaction` field instead.
=> Parse pleroma custom emoji reactions in notifications

examples/firefish_streaming.rs, examples/mastodon_streaming.rs, examples/mastodon_unauthorized_local.rs, examples/pleroma_streaming.rs, src/firefish/firefish.rs, src/friendica/friendica.rs, src/mastodon/mastodon.rs, src/megalodon.rs, src/pleroma/pleroma.rs
This PR attempts to infer the base streaming URL from the instance information instead of needing to manually provide it separately. It does this by calling `get_instance()` and retrieving the `streaming_api` URL if available, otherwise it will use the `base_url` of the client.
This is obviously a breaking change, since the function signatures for all the streaming functions have all become `async` and the `streaming_url` parameter is removed.
=> Infer streaming URL from instance information

Cargo.toml, examples/friendica_post_with_schedule.rs, examples/mastodon_post_with_schedule.rs, examples/pleroma_post_with_schedule.rs, src/firefish/entities/mod.rs, src/friendica/entities/mod.rs, src/pleroma/entities/marker.rs
This addresses the problems in #209 and #207 which were due to versions of crates that were specified at the 0.x level when various features were actually introduced in 0.x.y.
E.g.
- the and_utc() method was introduced in chrono 0.4.25
- the IntoUrl trait was implemented on String in reqwest 0.11.2
- env_filter requires regex >=1.3.0 (because the perf feature was added in that version)
- tungstenite and tokio-tungstenite require thiserror ^1.0.23
- tokio-util requires tokio 1.28
- tokio-tungstenite required log 0.4.8 and futures-util 0.3.28
- etc.
Commits:
- **Update minimal crate versions**
- **Reapply "fix: cleanup warnings"**
=> cleanup warnings

src/entities/account.rs, src/entities/follow_request.rs, src/firefish/entities/account.rs, src/firefish/entities/user_detail.rs, src/friendica/entities/account.rs, src/friendica/entities/follow_request.rs, src/gotosocial/entities/account.rs, src/mastodon/entities/account.rs, src/pleroma/entities/account.rs
Switching from `u32` to `i32` seems to fix the parsing failure when encountering a negative `followers_count`. I only saw the problem on Mastodon, so maybe this is overkill?
fixes https://github.com/h3poteto/megalodon-rs/issues/221
=> Switch followers_count to i32 to accept negative values

src/pleroma/pleroma.rs
Really small fix but it should make the API work on Pleroma, it currently 404s
=> Fix spelling of `markers` in API URL

src/firefish/firefish.rs, src/friendica/friendica.rs, src/gotosocial/gotosocial.rs, src/mastodon/mastodon.rs, src/megalodon.rs, src/pleroma/pleroma.rs
This pull request adds a helper to allow setting a private note on a Mastodon or GoToSocial account
=> Add set_account_note to Mastodon and GoToSocial

README.md
`client` is a `Result<_>` so needs to be unwrapped before using `verify_account_credentials`
=> Fix auth example syntax error in README
