src/error.rs
src/mastodon/api_client.rs

refs #3 Handle HTTP status error

---

Cargo.toml
examples/mastodon_streaming.rs
src/entities/application.rs
src/entities/card.rs
src/entities/conversation.rs
src/entities/field.rs
src/entities/history.rs
src/entities/mention.rs
src/entities/notification.rs
src/entities/poll.rs
src/entities/poll_option.rs
src/entities/preferences.rs
src/entities/reaction.rs
src/entities/status.rs
src/entities/tag.rs
src/error.rs
src/lib.rs
src/mastodon/api_client.rs
src/mastodon/entities/card.rs
src/mastodon/entities/field.rs
src/mastodon/entities/filter.rs
src/mastodon/entities/notification.rs
src/mastodon/entities/preferences.rs
src/mastodon/entities/status.rs
src/mastodon/mastodon.rs
src/mastodon/mod.rs
src/mastodon/web_socket.rs
src/megalodon.rs
src/streaming.rs

refs #4 Implement websocket streaming for Mastodon

---

Cargo.toml
examples/pleroma_authorization.rs
examples/pleroma_credentials.rs
examples/pleroma_instance.rs
examples/pleroma_streaming.rs
src/pleroma/api_client.rs
src/pleroma/entities/status.rs
src/pleroma/mod.rs
src/pleroma/oauth.rs
src/pleroma/pleroma.rs
src/pleroma/web_socket.rs

refs #5 Add pleroma api client

---

Cargo.toml

I had a hard time finding the source repository for this crate, so I figured I could contribute something to make it less hard for someone else :laughing:

Add links to repository

---

Cargo.toml
examples/mastodon_streaming.rs
examples/pleroma_streaming.rs
src/mastodon/web_socket.rs
src/pleroma/web_socket.rs

refs #28 Use env_logger instead of print log

---

examples/pleroma_post_with_media.rs
src/pleroma/api_client.rs
src/pleroma/pleroma.rs

Fix array serialization for Pleroma

---

examples/mastodon_media.rs
examples/mastodon_post_with_media.rs
examples/pleroma_post_with_media.rs
src/entities/async_attachment.rs
src/entities/mod.rs
src/error.rs
src/mastodon/api_client.rs
src/mastodon/entities/attachment.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

refs #47 Use /api/v2/media for uploading media

---

examples/pleroma_streaming.rs
src/mastodon/web_socket.rs
src/pleroma/web_socket.rs

refs #42 Implement auto-reconnect for web socket

---

src/mastodon/web_socket.rs
src/pleroma/web_socket.rs

And if an error has occurred too.

Auto-reconnect WebSocket if no messages are received for few minutes

---

src/pleroma/pleroma.rs

Follow up #58 fields_attributes for pleroma

---

examples/mastodon_streaming.rs
examples/pleroma_streaming.rs
src/mastodon/web_socket.rs
src/pleroma/web_socket.rs
src/streaming.rs

refs #61 Handle status.update event in websocket

---

src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

refs #61 Add an API to edit status

---

src/entities/tag.rs
src/mastodon/entities/tag.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/entities/tag.rs
src/pleroma/pleroma.rs

refs #61 Add APIs regarding tags

---

examples/pleroma_notifications.rs
src/entities/notification.rs
src/mastodon/entities/notification.rs
src/pleroma/entities/notification.rs

refs #83 Handle move notification type for Pleroma

---

Cargo.toml
examples/mastodon_unauthorized_local.rs
src/mastodon/web_socket.rs
src/pleroma/web_socket.rs

Give up streaming when it returns unauthorized

---

src/detector.rs

Add support to treat Wildebeest as Mastodon

---

src/friendica/friendica.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

refs https://github.com/h3poteto/megalodon/pull/1819

Add a method to get followed_tags

---

src/entities/report.rs
src/friendica/entities/report.rs
src/mastodon/entities/report.rs
src/pleroma/entities/report.rs

* Add action_taken_at for Mastodon
* Remove unsupported field from Pleroma report

Adjust report entity

---

src/pleroma/pleroma.rs

Pleroma does not support follow/unfollow tags

Remove tags API from Pleroma

---

examples/pleroma_conversations.rs
src/friendica/friendica.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

 refs #148 Fix get_conversation_timeline type 

---

src/firefish/firefish.rs

Copy from https://github.com/h3poteto/megalodon/pull/1921

Convert emoji to Firefish reaction

---

.github/workflows/example.yml
Cargo.toml

 refs #53 Add native-tls and rustls-tls features @h3poteto

---

src/pleroma/pleroma.rs

Refs: https://github.com/h3poteto/megalodon/pull/2152

Receive emoji name (not shortcode) in custom emoji reaction API

---

src/pleroma/pleroma.rs

Reverts h3poteto/megalodon-rs#190
We don't need it
https://github.com/h3poteto/megalodon/pull/2153

Revert "Receive emoji name (not shortcode) in custom emoji reaction API"

---

src/mastodon/mastodon.rs

This fixes the https://github.com/h3poteto/megalodon-rs/issues/180

Fix RequestError when trying to delete a status from mastodon

---

examples/pleroma_delete_status.rs
src/pleroma/pleroma.rs

Backport for Pleroma: https://github.com/h3poteto/megalodon-rs/pull/193

Fix RequestError in delete_status for Pleroma

---

src/pleroma/entities/instance.rs

refs #196 Fix pleroma metadata birthday_min_age and birthday_required

---

src/mastodon/mastodon.rs

while using the crates, from time to time the crates failed with the error : 
```            
missing field `scheduled_at` at line 1 column 2381    
```
after investigation, it was because i was trying to schedule some toot in less than 5 minutes and it's not allowed, see : https://docs.joinmastodon.org/methods/statuses/#form-data-parameters 
in such case the mastodon server ignore the field, and accept the toot
my proposal is to handle the error the same way : send the toot right now.

do not schedule toot on mastodon if scheduled_at is less than 5 minutes in the future

---

examples/friendica_post_with_schedule.rs
examples/mastodon_post_with_schedule.rs
examples/pleroma_post_with_schedule.rs
src/firefish/entities/mod.rs
src/friendica/entities/mod.rs
src/pleroma/entities/marker.rs

Reverts h3poteto/megalodon-rs#207

Revert "fix: cleanup warnings"

---

src/firefish/firefish.rs
src/friendica/friendica.rs
src/gotosocial/gotosocial.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

refs #229 Add pleroma methods

---

src/firefish/firefish.rs
src/friendica/friendica.rs
src/gotosocial/gotosocial.rs
src/mastodon/mastodon.rs
src/megalodon.rs
src/pleroma/pleroma.rs

refs #202 Add accounts lookup method

---

src/detector.rs
src/gotosocial/gotosocial.rs
src/megalodon.rs

refs https://github.com/h3poteto/megalodon/pull/2211

Add only_public option to get_account_statuses for Gotosocial

---

src/pleroma/entities/notification.rs

refs https://github.com/h3poteto/megalodon/pull/2212

Add Status as a Pleroma NotificationType

---

src/detector.rs
src/entities/notification.rs
src/entities/preferences.rs
src/entities/status.rs
src/error.rs
src/firefish/api_client.rs
src/firefish/entities/note.rs
src/firefish/firefish.rs
src/firefish/web_socket.rs
src/friendica/api_client.rs
src/friendica/entities/status.rs
src/friendica/friendica.rs
src/gotosocial/api_client.rs
src/gotosocial/entities/status.rs
src/gotosocial/gotosocial.rs
src/gotosocial/web_socket.rs
src/mastodon/api_client.rs
src/mastodon/entities/status.rs
src/mastodon/mastodon.rs
src/mastodon/web_socket.rs
src/megalodon.rs
src/pleroma/api_client.rs
src/pleroma/entities/notification.rs
src/pleroma/pleroma.rs
src/pleroma/web_socket.rs

feat: add headers to error type

---

src/mastodon/mastodon.rs

refs #260 Handle empty response in dismiss notifications

---

src/detector.rs

refs #259 Support Sharkey as Mastodon

---

src/pleroma/pleroma.rs

refs https://github.com/h3poteto/megalodon/pull/2243

pleroma: Deprecated API replace

---

examples/pixelfed_timeline.rs
src/pixelfed/pixelfed.rs

refs https://github.com/h3poteto/megalodon/pull/2248

Add remote flag to pixelfed public timeline

---

examples/firefish_streaming.rs
examples/gotosocial_streaming.rs
examples/mastodon_streaming.rs
examples/mastodon_unauthorized_local.rs
examples/pixelfed_streaming.rs
examples/pleroma_streaming.rs
src/firefish/web_socket.rs
src/friendica/web_socket.rs
src/gotosocial/web_socket.rs
src/mastodon/web_socket.rs
src/pixelfed/web_socket.rs
src/pleroma/web_socket.rs
src/streaming.rs

feat: allow async callback

---

src/mastodon/entities/status.rs

https://codeberg.org/fediverse/fep/src/branch/main/fep/044f/fep-044f.md https://github.com/mastodon/mastodon/pull/34370
While querying a tag timeline, I realized some statuses couldn't be parsed properly.
I tracked it down to quoted statuses.
I updated the struct to support at least decoding. More work might be required later on (especially for exposing the status id for shallow quotes).
The following request shows that the schema is different from what is expected:
```
$ curl -s 'https://dice.camp/api/v1/timelines/tag/WarhammerCommunity?only_media=true&limit=1&min_id=114919300388880370' | jq '.[0].quote | keys'
[
"quoted_status",
"state"
]
```

Support consent-respecting quote posts
